# Generated by Django 6.0.4 on 2026-04-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.TextField()),
                ('score', models.IntegerField()),
                ('match_score', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('jobs', models.TextField()),
            ],
        ),
    ]
