# Generated by Django 6.0.4 on 2026-04-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumerecord',
            name='ai_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumerecord',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumerecord',
            name='target_role',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
